/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.57
 * Generated at: 2021-10-19 19:30:15 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.view.ocr;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import poly.util.CmmUtil;
import java.util.List;
import poly.dto.OcrDTO;

public final class main_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("poly.util.CmmUtil");
    _jspx_imports_classes.add("poly.dto.OcrDTO");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");


	String ss_user_id = CmmUtil.nvl((String)session.getAttribute("ss_user_id"));
	String ss_user_pwd = CmmUtil.nvl((String)session.getAttribute("ss_user_id"));
	String ss_user_name = CmmUtil.nvl((String)session.getAttribute("ss_user_name"));
	
	List<OcrDTO> ocrList = ((List<OcrDTO>)request.getAttribute("ocrList"));
	

      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("    <head>\r\n");
      out.write("        <meta charset=\"utf-8\" />\r\n");
      out.write("        <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\" />\r\n");
      out.write("        <meta name=\"description\" content=\"\" />\r\n");
      out.write("        <meta name=\"author\" content=\"\" />\r\n");
      out.write("        <title>Start MedicineProject</title>\r\n");
      out.write("        <!-- Favicon-->\r\n");
      out.write("        <link rel=\"icon\" type=\"image/x-icon\" href=\"../resource/assets/favicon.ico\" />\r\n");
      out.write("        <!-- Font Awesome icons (free version)-->\r\n");
      out.write("        <script src=\"https://use.fontawesome.com/releases/v5.15.3/js/all.js\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("        <!-- Google fonts-->\r\n");
      out.write("        <link href=\"https://fonts.googleapis.com/css?family=Montserrat:400,700\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("        <link href=\"https://fonts.googleapis.com/css?family=Lato:400,700,400italic,700italic\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("        <!-- Core theme CSS (includes Bootstrap)-->\r\n");
      out.write("        <link href=\"../resource/css/styles.css\" rel=\"stylesheet\" />\r\n");
      out.write("    </head>\r\n");
      out.write("</head>\r\n");
      out.write("    <body id=\"page-top\">\r\n");
      out.write("        <!-- Navigation-->\r\n");
      out.write("        <nav class=\"navbar navbar-expand-lg bg-secondary text-uppercase fixed-top\" id=\"mainNav\">\r\n");
      out.write("            <div class=\"container\">\r\n");
      out.write("                <a class=\"navbar-brand\" href=\"#page-top\">Start MDP</a>\r\n");
      out.write("                <button class=\"navbar-toggler text-uppercase font-weight-bold bg-primary text-white rounded\" type=\"button\" data-bs-toggle=\"collapse\" data-bs-target=\"#navbarResponsive\" aria-controls=\"navbarResponsive\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">\r\n");
      out.write("                    Menu\r\n");
      out.write("                    <i class=\"fas fa-bars\"></i>\r\n");
      out.write("                </button>\r\n");
      out.write("                <div class=\"collapse navbar-collapse\" id=\"navbarResponsive\">\r\n");
      out.write("                    <ul class=\"navbar-nav ms-auto\">\r\n");
      out.write("                    \t<li class=\"nav-item mx-0 mx-lg-1\"><a class=\"nav-link py-3 px-0 px-lg-3 rounded\" onclick=\"document.all.fileUpload.click()\" >Picture</a></li>\r\n");
      out.write("                        <li class=\"nav-item mx-0 mx-lg-1\"><a class=\"nav-link py-3 px-0 px-lg-3 rounded\" href=\"#about\">Logs</a></li>\r\n");
      out.write("                        <li class=\"nav-item mx-0 mx-lg-1\"><a class=\"nav-link py-3 px-0 px-lg-3 rounded\" href=\"#contact\">Contact</a></li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                    \r\n");
      out.write("                    <a data-bs-toggle=\"modal\" data-bs-target=\"#ModalDiseane\" id=\"MDiseane\" style=\"display:none\" ></a>\r\n");
      out.write("                    <a data-bs-toggle=\"modal\" data-bs-target=\"#resultOcr\" id=\"TextOcr\" style=\"display:none\" ></a>\r\n");
      out.write("                    \r\n");
      out.write("                    <!-- Nonne 구간 안보이지만 Insert를 위한 중요한 부분 -->\r\n");
      out.write("                    <form enctype=\"multipart/form-data\" method=\"post\" action=\"../ocr/fileUpload.do\" >\r\n");
      out.write("                    \t<input type=\"file\" name=\"fileUpload\" id=\"fileUpload\" style=\"display:none\" accept=\"image/*\" onchange=\"fileSelect(this)\"/>\r\n");
      out.write("                    \t<input type=\"submit\" name=\"fileInsert\" id=\"fileInsert\" style=\"display:none\" />\r\n");
      out.write("                    \t\r\n");
      out.write("                    </form>\r\n");
      out.write("                    <script>\r\n");
      out.write("                \r\n");
      out.write("\t                    <!--  FileSelect function start  -->\r\n");
      out.write("\t                  \tfunction fileSelect(input){\r\n");
      out.write("\t                  \t\t\r\n");
      out.write("\t                  \t\tvar file_src = input.files[0];\r\n");
      out.write("\t                  \t\t\r\n");
      out.write("\t                  \t\t// 미리만들어 놓은 div에 text추가\r\n");
      out.write("\t                  \t\tvar file_name = document.getElementById('fileUpload');\r\n");
      out.write("\t                  \t\tfile_name.textContent = file_src.file_name;\r\n");
      out.write("\t                  \t\t\r\n");
      out.write("\t                  \t\tnewImage = document.createElement(\"img\");\r\n");
      out.write("\t                  \t\tnewImage.setAttribute(\"class\", 'img')\r\n");
      out.write("\t                  \t\t\r\n");
      out.write("\t                  \t\tnewImage.src = URL.createObjectURL(file_src);\r\n");
      out.write("\t                  \t\t\r\n");
      out.write("\t                  \t\tnewImage.style.width = \"100%\";\r\n");
      out.write("\t                  \t    newImage.style.height = \"100%\";\r\n");
      out.write("\t                  \t    newImage.style.objectFit = \"contain\";\r\n");
      out.write("\t                  \t    newImage.id = \"OcrID\";\r\n");
      out.write("\t                  \t\t\r\n");
      out.write("\t                  \t\tvar container = document.getElementById('Select_image');\r\n");
      out.write("\t                  \t    container.appendChild(newImage);\r\n");
      out.write("\t                  \t\t\r\n");
      out.write("\t                  \t\tif(file_name != null){\r\n");
      out.write("\t                  \t\t\t\r\n");
      out.write("\t                  \t\t\tdocument.all.MDiseane.click();\r\n");
      out.write("\t                  \t\t\t\r\n");
      out.write("\t                  \t\t}else {\r\n");
      out.write("\t                  \t\t\t\r\n");
      out.write("\t                  \t\t\talert(\"파일 선택은 필수 입니다\");\r\n");
      out.write("\t                  \t\t\t\r\n");
      out.write("\t                  \t\t}\r\n");
      out.write("\t                  \t\r\n");
      out.write("\t                  \t\t\r\n");
      out.write("\t                  \t}\r\n");
      out.write("\t                  \t\r\n");
      out.write("\t                  \r\n");
      out.write("\t                  \t\r\n");
      out.write("                    </script>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </nav>\r\n");
      out.write("        \r\n");
      out.write("                \r\n");
      out.write("        <div class=\"portfolio-modal modal fade\" id=\"ModalDiseane\" tabindex=\"-1\" aria-labelledby=\"MDiseane\" aria-hidden=\"true\">\r\n");
      out.write("            <div class=\"modal-dialog modal-xl\">\r\n");
      out.write("                <div class=\"modal-content\">\r\n");
      out.write("                    <div class=\"modal-header border-0\"><button class=\"btn-close\" type=\"button\" data-bs-dismiss=\"modal\" aria-label=\"Close\"></button></div>\r\n");
      out.write("                    <div class=\"modal-body text-center pb-5\">\r\n");
      out.write("                        <div class=\"container\" id=\"Medicine_no\">\r\n");
      out.write("                            <div class=\"row justify-content-center\">\r\n");
      out.write("                                <div class=\"col-lg-8\">\r\n");
      out.write("                                    <!-- Portfolio Modal - Title-->\r\n");
      out.write("                                    <h2 class=\"portfolio-modal-title text-secondary text-uppercase mb-0\">처방 추가하기</h2>\r\n");
      out.write("                                    <!-- Icon Divider-->\r\n");
      out.write("                                    <div class=\"divider-custom\">\r\n");
      out.write("                                    \t<input type=\"text\" name=\"medicine_cnt\" style=\"display:none\" />\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <!-- Portfolio Modal - Image-->\r\n");
      out.write("                                    \r\n");
      out.write("                                    <!-- Portfolio Modal - Text-->\r\n");
      out.write("                                    <p class=\"mb-4\">선택한 이미지</p>\r\n");
      out.write("                                    <div id=\"Select_image\">\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <button class=\"btn btn-primary\" id=\"MBDiseane\" onclick=\"fileInsert()\">\r\n");
      out.write("                                        Next\r\n");
      out.write("                                    </button>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div> \r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        \r\n");
      out.write("        <script>\r\n");
      out.write("        \tfunction fileInsert(){\r\n");
      out.write("        \t\t\r\n");
      out.write("        \t\tdocument.all.fileInsert.click();\r\n");
      out.write("        \t\t\r\n");
      out.write("        \t}\r\n");
      out.write("        </script>\r\n");
      out.write("        <div class=\"portfolio-modal modal fade\" id=\"resultOcr\" tabindex=\"-1\" aria-labelledby=\"resultOcr\" aria-hidden=\"true\">\r\n");
      out.write("            <div class=\"modal-dialog modal-xl\">\r\n");
      out.write("                <div class=\"modal-content\">\r\n");
      out.write("                    <div class=\"modal-header border-0\"><button class=\"btn-close\" type=\"button\" data-bs-dismiss=\"modal\" aria-label=\"Close\"></button></div>\r\n");
      out.write("                    <div class=\"modal-body text-center pb-5\">\r\n");
      out.write("                        <div class=\"container\" id=\"Medicine_no\">\r\n");
      out.write("                            <div class=\"row justify-content-center\">\r\n");
      out.write("                                <div class=\"col-lg-8\">\r\n");
      out.write("                                    <!-- Portfolio Modal - Title-->\r\n");
      out.write("                                    <h2 class=\"portfolio-modal-title text-secondary text-uppercase mb-0\">처방된 약물</h2>\r\n");
      out.write("                                    <!-- Icon Divider-->\r\n");
      out.write("                                    <div class=\"divider-custom\"></div>\r\n");
      out.write("                                    <!-- Portfolio Modal - Image-->\r\n");
      out.write("                                    \r\n");
      out.write("                                    <!-- Portfolio Modal - Text-->\r\n");
      out.write("                                    \r\n");
      out.write("                                    <p class=\"mb-4\">다시 작성해 주세요! </p>\r\n");
      out.write("\t                                    <div class=\"resultText\">\r\n");
      out.write("\t\t\t\t\t\t\t\t     \t\t<div>\r\n");
      out.write("\t\t\t\t\t\t\t\t     \t\t\t<input type=\"text\" name=\"medicine_name\" value=\"\"/>\r\n");
      out.write("\t\t\t\t\t\t\t\t     \t\t</div>\t\r\n");
      out.write("\t                                    </div>\r\n");
      out.write("                                    <button class=\"btn btn-primary\" id=\"MBDiseane\" onclick=\"OcrText()\">\r\n");
      out.write("                                        Next\r\n");
      out.write("                                    </button>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        \r\n");
      out.write("        \r\n");
      out.write("        <!-- Masthead-->\r\n");
      out.write("        <header class=\"masthead bg-primary text-white text-center\">\r\n");
      out.write("            <div class=\"container d-flex align-items-center flex-column\">\r\n");
      out.write("                <!-- Masthead Avatar Image-->\r\n");
      out.write("                <img class=\"masthead-avatar mb-5\" src=\"../resource/assets/img/avataaars.svg\" alt=\"...\" />\r\n");
      out.write("                <!-- Masthead Heading-->\r\n");
      out.write("                <h1 class=\"masthead-heading text-uppercase mb-0\">");
      out.print(ss_user_name );
      out.write("님 <br>Start MDP</h1>\r\n");
      out.write("                <!-- Icon Divider-->\r\n");
      out.write("                <div class=\"divider-custom divider-light\">\r\n");
      out.write("                    <div class=\"divider-custom-line\"></div>\r\n");
      out.write("                    <div class=\"divider-custom-icon\"><i class=\"fas fa-star\"></i></div>\r\n");
      out.write("                    <div class=\"divider-custom-line\"></div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <!-- Masthead Subheading-->\r\n");
      out.write("                <p class=\"masthead-subheading font-weight-light mb-0\">병원마다 - 다르게 처방되는 약들 - 바른 처방일까?</p>\r\n");
      out.write("            </div>\r\n");
      out.write("        </header>\r\n");
      out.write("        \r\n");
      out.write("        <script>\r\n");
      out.write("        \tfunction OcrList(){ \r\n");
      out.write("        \t\tvar medicine_no = $('#medicine_no').val();\r\n");
      out.write("        \t\t\r\n");
      out.write("        \t\tif($('#medicine_no').val() == \"\"){\r\n");
      out.write("    \t\t\t\t$('#medicine_no').focus();\r\n");
      out.write("    \t\t\t}\r\n");
      out.write("    \t\t\t\r\n");
      out.write("    \t\t\tconsole.log(\"medicine_no : \" + medicine_no);\r\n");
      out.write("    \t\t\t\r\n");
      out.write("    \t\t\t$.ajax({\r\n");
      out.write("    \t\t\t\turl : '/ocr/ocrList.do',\r\n");
      out.write("    \t\t\t\ttype : 'post',\r\n");
      out.write("    \t\t\t\tdata : {\r\n");
      out.write("    \t\t\t\t\t\"medicine_no\" : medicine_no\r\n");
      out.write("    \t\t\t\t},\r\n");
      out.write("    \t\t\t\tsuccess : function(data) { \r\n");
      out.write("    \t\t\t\t\tconsole.log(\"test\");\r\n");
      out.write("    \t\t\t\t\t\r\n");
      out.write("    \t\t\t\t\tvar userHTML = \"\"; // 게시판위의 나타내어 줄 userId, userProfile 정보 들고오기\r\n");
      out.write("    \t\t\t\t\tuserHTML = '<div class=\"portfolio-item mx-auto\" data-bs-toggle=\"modal\" data-bs-target=\"#portfolioModal1\">';\r\n");
      out.write("    \t\t\t\t\tuserHTML = '<div class=\"portfolio-item-caption d-flex align-items-center justify-content-center h-100 w-100\">;\r\n");
      out.write("    \t\t\t\t\tuserHTML = '<div class=\"portfolio-item-caption-content text-center text-white\"><i class=\"fas fa-plus fa-3x\"></i></div></div>';\r\n");
      out.write("    \t\t\t\t\tuserHTML = '<div name=\"medicine_no\" style=\"display:none\">'+data.getMedicine_no()+'\"</div>';\r\n");
      out.write("    \t\t\t\t\tuserHTML = '<img class=\"img-fluid\" src=\" '+ data.getSave_file_path()' \" alt=\"...\" /></div></div>';\r\n");
      out.write("    \t\t\t\t\t\r\n");
      out.write("    \t\t\t\t\tif(data.length == 0){\r\n");
      out.write("    \t\t\t\t\t\tuserHTML = '<div class=\"portfolio-item mx-auto\" data-bs-toggle=\"modal\" data-bs-target=\"#portfolioModal1\">';\r\n");
      out.write("    \t\t\t\t\t\tuserHTML = '<div class=\"portfolio-item-caption d-flex align-items-center justify-content-center h-100 w-100\">';\r\n");
      out.write("    \t\t\t\t\t\tuserHTML = '<div class=\"portfolio-item-caption-content text-center text-white\"><i class=\"fas fa-plus fa-3x\"></i></div></div>';\r\n");
      out.write("    \t\t\t\t\t\tuserHTML = '<img class=\"img-fluid\" src=\"../resource/assets/img/portfolio/cabin.png\" alt=\"...\" /></div></div> '\r\n");
      out.write("    \t\t\t\t\t}else{\r\n");
      out.write("    \t\t\t\t\t\tfor(var i = 0;  i < data.lenth(); i++){\r\n");
      out.write("    \t\t\t\t\t\t\tuserHTML = '<div class=\"portfolio-item mx-auto\" data-bs-toggle=\"modal\" data-bs-target=\"#portfolioModal1\">';\r\n");
      out.write("    \t    \t\t\t\t\tuserHTML = '<div class=\"portfolio-item-caption d-flex align-items-center justify-content-center h-100 w-100\">;\r\n");
      out.write("    \t    \t\t\t\t\tuserHTML = '<div class=\"portfolio-item-caption-content text-center text-white\"><i class=\"fas fa-plus fa-3x\"></i></div></div>';\r\n");
      out.write("    \t    \t\t\t\t\tuserHTML = '<div name=\"medicine_no\" style=\"display:none\">'+data.getMedicine_no()+'\"</div>';\r\n");
      out.write("    \t    \t\t\t\t\tuserHTML = '<img class=\"img-fluid\" src=\" '+ data.getSave_file_path()' \" alt=\"...\" /></div></div>';\r\n");
      out.write("    \t\t\t\t\t\t}\r\n");
      out.write("    \t\t\t\t\t\t$(\"#col-md-6 col-lg-4 mb-5\").html(userHTML);\r\n");
      out.write("    \t\t\t\t\t}\r\n");
      out.write("    \t\t\t\t}\r\n");
      out.write("    \t\t\t});\r\n");
      out.write("        \t\t\r\n");
      out.write("        \t}\r\n");
      out.write("        </script>\r\n");
      out.write("        \r\n");
      out.write("        \r\n");
      out.write("        <!-- Portfolio Section-->\r\n");
      out.write("        <section class=\"page-section portfolio\" id=\"portfolio\">\r\n");
      out.write("            <div class=\"container\">\r\n");
      out.write("                <!-- Portfolio Section Heading-->\r\n");
      out.write("                <h2 class=\"page-section-heading text-center text-uppercase text-secondary mb-0\">지난 처방들</h2>\r\n");
      out.write("                <!-- Icon Divider-->\r\n");
      out.write("                <div class=\"divider-custom\">\r\n");
      out.write("                    <div class=\"divider-custom-line\"></div>\r\n");
      out.write("                    <div class=\"divider-custom-icon\"><i class=\"fas fa-star\"></i></div>\r\n");
      out.write("                    <div class=\"divider-custom-line\"></div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <!-- Portfolio Grid Items-->\r\n");
      out.write("                <div class=\"row justify-content-center\">\r\n");
      out.write("                \r\n");
      out.write("                 \t<!-- Ajax 구간 시작 -->\r\n");
      out.write("                 \t<!-- List기준으로 불러오기 -->\r\n");
      out.write("                    <!-- Portfolio Item 1-->\r\n");
      out.write("                    <div class=\"col-md-6 col-lg-4 mb-5\">\r\n");
      out.write("                    ");
for(OcrDTO Medicine : ocrList ) {
      out.write("\r\n");
      out.write("                    \t<div name=\"medicine_no\" style=\"display:none\"> ");
      out.print(Medicine.getMedicine_no());
      out.write(" </div>\r\n");
      out.write("                        <div class=\"portfolio-item mx-auto\" data-bs-toggle=\"modal\" data-bs-target=\"#portfolioModal");
      out.print(Medicine.getMedicine_no());
      out.write("\">\r\n");
      out.write("                            <div class=\"portfolio-item-caption d-flex align-items-center justify-content-center h-100 w-100\">\r\n");
      out.write("                                <div class=\"portfolio-item-caption-content text-center text-white\"><i class=\"fas fa-plus fa-3x\"></i></div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <img class=\"img-fluid\" src=\"");
      out.print(Medicine.getSave_file_path() );
      out.write("\" alt=\"...\" />\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                     <!-- Ajax 구간 끝-->\r\n");
      out.write("                     ");
} 
      out.write("\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>                                  \r\n");
      out.write("        </section>\r\n");
      out.write("        <!-- Portfolio Modal -->\r\n");
      out.write("        ");
for(OcrDTO Medicine : ocrList ) {
      out.write("\r\n");
      out.write("        <div class=\"portfolio-modal modal fade\" id=\"portfolioModal");
      out.print(Medicine.getMedicine_no());
      out.write("\" tabindex=\"-1\" aria-labelledby=\"portfolioModal");
      out.print(Medicine.getMedicine_no());
      out.write("\" aria-hidden=\"true\">\r\n");
      out.write("            <div class=\"modal-dialog modal-xl\">");
      out.print(Medicine.getMedicine_no());
      out.write("\r\n");
      out.write("                <div class=\"modal-content\">\r\n");
      out.write("                    <div class=\"modal-header border-0\"><button class=\"btn-close\" type=\"button\" data-bs-dismiss=\"modal\" aria-label=\"Close\"></button></div>\r\n");
      out.write("                    <div class=\"modal-body text-center pb-5\">\r\n");
      out.write("                        <div class=\"container\">\r\n");
      out.write("                            <div class=\"row justify-content-center\">\r\n");
      out.write("                                <div class=\"col-lg-8\">\r\n");
      out.write("                                    <!-- Portfolio Modal - Title--><!-- 처방받은 날짜를 제목으로 띄우기 -->\r\n");
      out.write("                                    <h2 class=\"portfolio-modal-title text-secondary text-uppercase mb-0\">처방전 <!-- CRE_DT --></h2>\r\n");
      out.write("                                    <!-- Icon Divider-->\r\n");
      out.write("                                    <div class=\"divider-custom\">\r\n");
      out.write("                                        <div class=\"divider-custom-line\"></div>\r\n");
      out.write("                                        <div class=\"divider-custom-icon\"><i class=\"fas fa-star\"></i></div>\r\n");
      out.write("                                        <div class=\"divider-custom-line\"></div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <!-- Portfolio Modal - Image-->\r\n");
      out.write("                                    <!-- Image_no 기준으로 이미지 경로 불러오기-->\r\n");
      out.write("                                    <img class=\"img-fluid rounded mb-5\" src=\"");
      out.print(Medicine.getSave_file_path() );
      out.write("\" alt=\"...\" />\r\n");
      out.write("                                    <!-- Portfolio Modal - Text-->\r\n");
      out.write("                                    <p class=\"mb-4\"><!-- Medicine_name(약 이름 ) 나열하기 --></p>\r\n");
      out.write("                                    <button class=\"btn btn-primary\" href=\"#!\" data-bs-dismiss=\"modal\">\r\n");
      out.write("                                        <i class=\"fas fa-times fa-fw\"></i>\r\n");
      out.write("                                        Close Window\r\n");
      out.write("                                    </button>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        ");
} 
      out.write("\r\n");
      out.write("        <!-- Footer-->\r\n");
      out.write("        <footer class=\"footer text-center\">\r\n");
      out.write("            <div class=\"container\">\r\n");
      out.write("                <div class=\"row\">\r\n");
      out.write("                    <!-- Footer Location-->\r\n");
      out.write("                    <div class=\"col-lg-4 mb-5 mb-lg-0\">\r\n");
      out.write("                        <h4 class=\"text-uppercase mb-4\">Developer Information</h4>\r\n");
      out.write("                        <p class=\"lead mb-0\">\r\n");
      out.write("                            1997 - 01 - 21 / MEN\r\n");
      out.write("                            <br />\r\n");
      out.write("                            Republic of Korea \r\n");
      out.write("                        </p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <!-- Footer Social Icons-->\r\n");
      out.write("                    <!-- Footer About Text-->\r\n");
      out.write("                    <div class=\"col-lg-4\">\r\n");
      out.write("                        <p class=\"lead mb-0\">\r\n");
      out.write("                            혼자 자랑해보는 \r\n");
      out.write("                            <a href=\"https://github.com/gkawlals\">My Git page</a>\r\n");
      out.write("                            .\r\n");
      out.write("                        </p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </footer>\r\n");
      out.write("        <!-- Copyright Section-->\r\n");
      out.write("        <div class=\"copyright py-4 text-center text-white\">\r\n");
      out.write("            <div class=\"container\"><small>Copyright &copy; Your Website 2021</small></div>\r\n");
      out.write("        </div>\r\n");
      out.write("        \r\n");
      out.write("        <!-- Modal Ajax 구간 -->\r\n");
      out.write("        <!-- Ajax 구간 끝  -->\r\n");
      out.write("        <!-- 처방전을 추가할 Modal Page -->\r\n");
      out.write("        <div class=\"portfolio-modal modal fade\" id=\"AddModal\" tabindex=\"-1\" aria-labelledby=\"AddMedicien\" aria-hidden=\"true\">\r\n");
      out.write("            <div class=\"modal-dialog modal-xl\">\r\n");
      out.write("                <div class=\"modal-content\">\r\n");
      out.write("                    <div class=\"modal-header border-0\"><button class=\"btn-close\" type=\"button\" data-bs-dismiss=\"modal\" aria-label=\"Close\"></button></div>\r\n");
      out.write("                    <div class=\"modal-body text-center pb-5\">\r\n");
      out.write("                        <div class=\"container\" id=\"Medicine_no\">\r\n");
      out.write("                            <div class=\"row justify-content-center\">\r\n");
      out.write("                                <div class=\"col-lg-8\">\r\n");
      out.write("                                    <!-- Portfolio Modal - Title-->\r\n");
      out.write("                                    <h2 class=\"portfolio-modal-title text-secondary text-uppercase mb-0\">처방 추가하기</h2>\r\n");
      out.write("                                    <!-- Icon Divider-->\r\n");
      out.write("                                    <div class=\"divider-custom\">\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <!-- Portfolio Modal - Image-->\r\n");
      out.write("                                    \r\n");
      out.write("                                    <!-- Portfolio Modal - Text-->\r\n");
      out.write("                                    <p class=\"mb-4\">처방받은 날짜을 입력해주세요<input type=\"text\" name=\"receive_dt\" id=\"receive_dt\" style=\"width: 50%;\"> </p>\r\n");
      out.write("                                    <button class=\"btn btn-primary\" onclick=\"fileSelect()\">\r\n");
      out.write("                                        Next\r\n");
      out.write("                                    </button>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <!-- Bootstrap core JS-->\r\n");
      out.write("        <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("        <!-- Core theme JS-->\r\n");
      out.write("        <script src=\"../resource/js/scripts.js\"></script>\r\n");
      out.write("        <!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *-->\r\n");
      out.write("        <!-- * *                               SB Forms JS                               * *-->\r\n");
      out.write("        <!-- * * Activate your form at https://startbootstrap.com/solution/contact-forms * *-->\r\n");
      out.write("        <!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *-->\r\n");
      out.write("        <script src=\"https://cdn.startbootstrap.com/sb-forms-latest.js\"></script>\r\n");
      out.write("    </body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
